### ISSUE TITLE
Bug on Kodi Krypton 17.3

### ISSUE THREAD

**Issue by Orblux** [SylvainCecchetto/plugin.video.catchuptvandmore#12]
Hello,

I downloaded the Github version of the plugin but I can't succeed in enter in any category with the following logfile error :

```
ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
ERROR: Control 550 in window 10025 has been asked to focus, but it can't
NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
WARNING: CPythonInvoker(25): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
WARNING: CPythonInvoker(26): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
        Error Type: <class 'socket.error'>
        Error Contents: [Errno 98] Address already in use
        Traceback (most recent call last):
        File "/storage/.kodi/addons/plugin.video.mobdro/modules/akamaiSecureHD.py", line 274, in <module>
        httpd = server_class((HOST_NAME, PORT_NUMBER), MyHandler)
        File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
        File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
        File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
        File "/usr/lib/python2.7/socket.py", line 228, in meth
        error: [Errno 98] Address already in use
        -->End of Python script error report<--
````

It appears the plugin can't access to a directory and, then try to re-use some adress on error...
I tried to reboot the OS and launch again the plugin but it is the same error-log.

Feel free to ask me any other informations (and also in French if you prefer ^^)

Thank you for your your work and your plugin that sounds great!

**Comment by SylvainCecchetto** [comment]
Hello Orblux,

Sorry to be late for answer and thank you for your report.

On my side I never encountered this issue :-/
But in the log the error seems to be related to the "Mobdro — Akamai Secure HD" plugin that already use an "address" 0_o. I don't know this plugin but you can maybe try to disable it temporarily to see if there is any difference?

I'm waiting for your feedback!

Thanks

Sylvain

**Comment by SylvainCecchetto** [comment]
No answer --> Issue closed
