### ISSUE TITLE
Add download mode with the module 'script.module.youtube.dl'

### ISSUE THREAD

**Issue by wwark** [SylvainCecchetto/plugin.video.catchuptvandmore#19]
Bonjour,

Comme vu par mail, j'ouvre une issue pour cette nouvelle demande.

Merci,

**Comment by SylvainCecchetto** [comment]
Bonjour wwark,

Merci pour le rappel, j'y regarde tout de suite ;-)

**Comment by SylvainCecchetto** [comment]
TODO list:

* Settings
    * New tab "Download"
    * Download folder path

* In each channel python file in the "list_videos" function
    * Add a context menu to download video

To be continued...

**Comment by SylvainCecchetto** [comment]
Bon je viens de pusher sur la branche Dev un "début" de test avec Arte. e5358819dfb9fc9c23a335156a872d74e2f93ee9

En gros ce que j'ai fait :

* Dans addon.py
    * Ajout du callback "download_video" qui est appelé quand l'utilisateur choisit "Télécharger" sur une vidéo. Ce callback récupère l'URL de la vidéo avant de la donner à Youtube-dl

* Dans arte.py
    * Ajout dans la fonction "list_videos" du context menu "Download" avec en paramètre l'URL de la page HTML contenant la vidéo.

Donc ce qui se passe dans l'ordre chronologique :

1. Dans Arte.py quand on arrive dans la fonction "list_videos" on ajoute comme d'habitude chaque item correspondant à chaque vidéo du replay. Mais en plus on attribut à chaque item le context menu download avec l'URL de la page web de la vidéo
2. Si l'utilisateur fait "Entrer" la vidéo se lance comme avant (Kodi appelle get_video_url et lance le streaming). Mais si l'utilisateur fait clic droit sur la vidéo et choisit "Téléchargement" alors le callback "download_video" présent dans addon.py est appelé.
3. La fonction "download_video" reçoit comme paramètre l'URL de la page, il lui reste alors à appeler la fonction "get_video_url" du fichier python de la chaine concernée afin de récupérer l'URL de la vidéo.
4. Cette URL est donnée à Youtube-dl qui lance le téléchargement.

Bon ça c'est dans la théorie ... Mais dans la pratique je me retourne avec le message d'erreur "m3u8 download detected but ffmpeg or avconv could not be found" sur mon Mac. 

J'attends ton retour !

**Comment by wwark** [comment]
Merci  !  ça marche pour moi. (Débian avec Kodi 17.3)

J'ai testé avec le film "La femme et le TGV". J'ai ce fichier video présent dans mon répertoire "/tmp" 072393-000-A_SQ_0_VOF_03101071_MP4-2200_AMM-PTWEB_mHlRfchHH-072393-000-A_SQ_0_VOF_03101071_MP4-2200_AMM-PTWEB_mHlRfchHH.mp4

![image](https://user-images.githubusercontent.com/469461/27261276-6a3093c2-5440-11e7-981e-25009e148b32.png)

Je peux regarder dans la todo list afin d'ajouter les settings et le bouton download pour chaque video

Merci,

**Comment by SylvainCecchetto** [comment]
Ah cool alors !
Moi je pense que j'ai un problème lié à l'OS, il faut que je regarde ça de plus prêt !

Ah ben écoute avec plaisir, n'hésite pas si besoin ;)

**Comment by wwark** [comment]
Hello,

Désolé pour le délai, voici mon premier pull request.

Je me demande comment l'activer pour toutes les chaines car la fonction "list_videos" diffère pas mal suivant les chaines.

**Comment by wwark** [comment]
Autre point, depuis une mise à jour de Kodi ou du script YTDL. La popup Download n'affiche plus la progression deplus les fichiers téléchargés se nomment tous master-master.mp4.

**Comment by wwark** [comment]
J'obtien aussi l'erreur "m3u8 download detected but ffmpeg or avconv could not be found" sur ma box android (NvidiaShield)

**Comment by wwark** [comment]
J'ai pu ajouter le mode Download sur plusieurs chaines Françaises (pas regarder pour les cas des chaines belges)

Cas KO
* Numero 23 => Télécharge pas la bonne video (problème entre youtubedl et dailymotion) ?
* NRJ => KO
00:44:19.817 T:140574163412736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 320, in <module>
                                                common.plugin.run(window_title)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 293, in download_video
                                                url_video = channel.get_video_url(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 443, in inner_wrapper
                                                data = func(*args, **kwargs)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/nrj.py", line 421, in get_video_url
                                                attrs={'itemprop': 'contentUrl'})['content'].encode('utf-8')
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
* L'equipe TV non testé 
* BFM TV non testé

**Comment by wwark** [comment]
- [x] Downlaod Mode TV France TV (France 2, France 3, France 4, France 5, France Ô, La 1ère)
- [x] Downlaod Mode Groupe TF1 (TF1, LCI, TMC, HD1, NT1, Tfou, Xtra)
- [ ] Download Mode LCP Assemblée Nationale | Require Add Replay
- [x] Download Mode Gulli
- [x] Download Mode Arte (FR/DE)
- [x] Download Mode Numéro 23
- [x] Download Mode NRJ12/Cherie25
- [x] Download Mode Groupe M6 (M6, W9, 6Ter) 
- [ ] Download Mode Groupe BFMTV | KO (error) A investiguer ..
- [x] Download Mode L'équipe TV
- [x] Download Mode Groupe Canal + (CPlus (en clair), C8, CStar, CNews)
- [ ] Garder YoutubeDL (problème avec FFMPEG non présent sur Android, Problème sur MAC
- [ ] Nom de la vidéo télécharger (passer à YoutubeDL) Definir le format ?

**Comment by SylvainCecchetto** [comment]
Le problème de FFMPEG sur Mac est résolu pour moi. En fait Kodi n'intègre pas dans son PATH /usr/local/bin donc j'ai fait un lien symbolique de ffmpeg vers /usr/bin il me semble est plus de problème avec YouTube-DL sous Kodi

**Comment by SylvainCecchetto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [YouTube DL - Il faut dire à Youtube-DL de donner comme nom à la vidéo téléchargée le label de la vidéo qui est affichée dans Kodi](https://trello.com/c/wuEY7qmc/93-youtube-dl-il-faut-dire-%C3%A0-youtube-dl-de-donner-comme-nom-%C3%A0-la-vid%C3%A9o-t%C3%A9l%C3%A9charg%C3%A9e-le-label-de-la-vid%C3%A9o-qui-est-affich%C3%A9e-dans-kodi)

**Comment by osmoze06** [comment]
> Le problème de FFMPEG sur Mac est résolu pour moi. En fait Kodi n'intègre pas dans son PATH /usr/local/bin donc j'ai fait un lien symbolique de ffmpeg vers /usr/bin il me semble est plus de problème avec YouTube-DL sous Kodi

je ne parviens pas à télécharger quoique ce soit, j'ai besoin  d'aide svp
