### ISSUE TITLE
Météo TF1 KO

### ISSUE THREAD

**Issue by shnorbluk** [SylvainCecchetto/plugin.video.catchuptvandmore#26]
Bonjour,
Il n'est pas possible de voir la météo de TF1 en replay. J'ai cette erreur dans les logs:

14:40:51.893 T:509552727120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find_all'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 334, in <module>
                                                common.PLUGIN.run(window_title)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 260, in channel_entry
                                                return channel.channel_entry(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/tf1.py", line 64, in channel_entry
                                                return list_videos_categories(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 443, in inner_wrapper
                                                data = func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/tf1.py", line 233, in list_videos_categories
                                                for li in filters_1_soup.find_all('li'):
                                            AttributeError: 'NoneType' object has no attribute 'find_all'
                                            -->End of Python script error report<--
14:40:52.145 T:510324642896   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&next=list_videos_categories&program_url=http%3a%2f%2fmeteo.tf1.fr%2fmeteo-france%2f&window_title=M%c3%a9t%c3%a9o
14:40:52.146 T:510324642896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&next=list_videos_categories&program_url=http%3a%2f%2fmeteo.tf1.fr%2fmeteo-france%2f&window_title=M%c3%a9t%c3%a9o) failed

En regardant le code, je vois qu'il cherche à se connecter à http://meteo.tf1.fr/meteo-france/videos. Mais le serveur renvoie une page d'erreur 404, dans laquelle il cherche une balise &lt;ul class="grid">,  qu'il ne trouve pas. En fait, la catégorie météo n'est pas comme les autres catégories pour lesquelles une liste de vidéos est affichée. Il n'y a qu'une seule vidéo du bulletin météo qui est présentée sur le site de tf1, contrairement à l'application mytf1 sur android dans laquelle on a accès à plusieurs vidéos pour la météo.
Du coup, je vois 2 solutions pour corriger le problème:
- récupérer l'url de la vidéo dans la page  http://meteo.tf1.fr/meteo-france
- sniffer les requêtes HTTP de l'application Mytf1 pour trouver la requête qui lui permet de récupérer la liste des vidéos et leurs URL.

En attendant, merci pour le plugin Kodi, il me rend bien service.

**Comment by wwark** [comment]
Bonjour,

Merci pour avoir remonter ce problème.

Un fix est présent ici :
[https://github.com/SylvainCecchetto/plugin.video.catchuptvandmore/commit/5c929f3895a66f70f510a1abf53cfe6cddffed18](url)

Si c'est bon on pourra fermer cette "issue".

Wwark

**Comment by shnorbluk** [comment]
Bonjour,

Wow! Déjà! J'ai cherché à corriger moi-même pendant plusieurs heures mais je n'ai pas trouvé. Il est vrai que je ne connais pas le fonctionnement de Kodi et du plugin.

Pour revenir à la correction, je l'ai testée et cela fonctionne parfaitement. Tu peux fermer l'incident.

Un grand merci.

**Comment by wwark** [comment]
Merci à toi pour le test. Je ferme le ticket.
N'hésite pas à poster des PR ou des anomalies pour faire évoluer cet addon.

Wwark
