### ISSUE TITLE
Problème avec les chaines du groupe TF1

### ISSUE THREAD

**Issue by wwark** [SylvainCecchetto/plugin.video.catchuptvandmore#8]
Bonjour,

Voici l'erreur remontée avec les chaine du groupe TF1.

07:32:27.752 T:140028320605952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get_text'
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 282, in <module>
                                                common.plugin.run(window_title)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 239, in channel_entry
                                                return channel.channel_entry(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/tf1.py", line 44, in channel_entry
                                                return list_videos(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 443, in inner_wrapper
                                                data = func(*args, **kwargs)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/tf1.py", line 141, in list_videos
                                                video_type_string = li.find('strong').get_text().encode('utf-8')
                                            AttributeError: 'NoneType' object has no attribute 'get_text'
                                            -->End of Python script error report<--
07:32:27.774 T:140030823622400  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
07:32:27.974 T:140031597726592   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&next=list_videos&program_url=%2ftmc%2fquotidien-avec-yann-barthes&window_title=Quotidien%20avec%20Yann%20Barth%c3%a8s
07:32:27.975 T:140031597726592   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&next=list_videos&program_url=%2ftmc%2fquotidien-avec-yann-barthes&window_title=Quotidien%20avec%20Yann%20Barth%c3%a8s) failed

D'avance merci.

**Comment by SylvainCecchetto** [comment]
Bonjour wwark,

Je viens de faire quelques modifications sur la branche dev pour les chaines du groupes TF1. Normalement ça devrait fonctionner à nouveau.

Si tu as l'occasion de tester je suis preneur

Merci

**Comment by SylvainCecchetto** [comment]
Finalement j'ai préféré envoyer les modif aussi sur la branche master pour pouvoir rapidement soumettre la version corriger à la team kodi pour le repo officiel

**Comment by wwark** [comment]
J'ai pu testé et les chaines du groupe TF1 fonctionnent de nouveau.

Un grand merci :+1:

**Comment by SylvainCecchetto** [comment]
Merci à toi pour avoir remonté les problèmes !
