### ISSUE TITLE
Arte a changé son site

### ISSUE THREAD

**Issue by wwark** [SylvainCecchetto/plugin.video.catchuptvandmore#9]
Bonjour,

Voici l'erreur que je rencontre suite au changement du site Arte.

07:35:25.061 T:140030176708352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'genre'
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 282, in <module>
                                                common.plugin.run(window_title)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 239, in channel_entry
                                                return channel.channel_entry(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/arte.py", line 39, in channel_entry
                                                return list_shows(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 443, in inner_wrapper
                                                data = func(*args, **kwargs)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/arte.py", line 79, in list_shows
                                                emission_dict['genre'] = emission['genre'].encode('utf-8')
                                            KeyError: 'genre'
                                            -->End of Python script error report<--
07:35:25.079 T:140030823622400  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
07:35:25.271 T:140031597726592   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.arte.arte&channel_module=channels.fr.arte&channel_name=arte&next=list_shows_1&window_title=Arte
07:35:25.272 T:140031597726592   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.arte.arte&channel_module=channels.fr.arte&channel_name=arte&next=list_shows_1&window_title=Arte) failed

D'avance merci,

**Comment by SylvainCecchetto** [comment]
Bonjour wwark,

Merci pour tes deux retours ! Je dois avouer que malheureusement ça fait un petit moment que je n'ai pas avancé sur le plugin faute de temps ...

J'essaie ce week end de m'y replonger un peu ou alors la semaine prochaine. En attendant le PR sont les bienvenues ;-)

**Comment by SylvainCecchetto** [comment]
Normalement tout comme pour le groupe TF1, Arte doit de nouveau fonctionner sur la branche master

Merci de ton retour

**Comment by wwark** [comment]
J'ai pu tester. Arte fonctionne de nouveau !

Merci.
